apiVersion: aws.caas.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: backup-test
  namespace: default
  annotations:
    uptest.upbound.io/pre-delete-hook: ../testhooks/aws-release-delete.sh
spec:
  parameters:
    id: backup-test
    region: eu-central-1
    version: "1.27"
    iam:
      roleArn: arn:aws:iam::609897127049:role/AWSReservedSSO_AdministratorAccess_d703c73ed340fde7
    nodes:
      count: 3
      instanceType: t3.small
    gitops:
      url: https://github.com/upbound/caas-cluster-configuration
  writeConnectionSecretToRef:
    name: backup-test-kubeconfig
